# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       moe.smoothie.parkingchaos

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$

%define _buildhost Aurora Build Engine

Summary:    Parking Chaos
Version:    1.3.0.3
Release:    1
Group:      Amusements/Games
License:    GPL-3.0-or-later
URL:        https://github.com/salty-smoothie/aurora-parkingchaos
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(auroraapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Переполох на вашей парковке!
Parking Chaos - клон игры “Час пик” или “Пробки”, созданный с нуля на основе ParkMeeCrazy.
Переместите красный трактор к выходу справа, передвигая других с дороги.
Горизонтальные машины могут двигаться только влево и право, вертикальные-только вверх и вниз.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5  \
    VERSION=%{version} \
    RELEASE=%{release}

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%defattr(644,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
